### ISSUE TITLE
can't see the run window.

### ISSUE THREAD

**Issue by maichaide** [francostellari/NppPlugins#1]
It is possible to run python scripts! But when I edit the python script and run it again, the run window is too fast to view.
I close the python script file, then reopen it and run it again. I still can't see the run window.
a input() function in my python script but I cannot input again by runme plugins.
Please help, Thanks your works 👍 
[t1.zip](https://github.com/francostellari/NppPlugins/files/5610438/t1.zip)

**Comment by francostellari** [comment]
I'm not sure I understand your problem. RunMe performs the equivalent of double clicking your file.
Does it work when you execute the file directly.
In my case running your file shows every time the input prompt but not the print result because the window will close immediately.
If you want it to stay open you may add another input() at the end of the file.
