### ISSUE TITLE
Not responding when multiple sections found in .chm file

### ISSUE THREAD

**Issue by 3RUN** [francostellari/NppPlugins#8]
Hey! Thank you for the awesome plugin!

I'm using it to help users with navigating the manual. So they could select a predefined world and hit 'help' from context menu. However, if manual has several sections covering the selected word, whole notepad++ will freeze and stop responding. 

This is how it looks (translation Title bar: "Found sections" Below: "Select section and press "SHOW""):
![Alt text](https://i.ibb.co/cDR6jr1/bug.png "Bug preview")

Best regards!

**Comment by francostellari** [comment]
Can you please post the CHM file and languagehelp.ini?
Also what version of LanguageHelp are you using?
Thank you.

**Comment by 3RUN** [comment]
Sure! Here: [manual + ini.zip](https://github.com/francostellari/NppPlugins/files/6868840/manual.%2B.ini.zip)
As for the version, I'm using the latest one I could find (v1.74 (build 2021-04-23)).
Thank you!

**Comment by francostellari** [comment]
I have check your CHM file and I can reproduce the fail... although I'm not quite sure what the problem is.
It appears to be a problem only when you have "Keep the help window always on top" option enabled and when the CHM is not open and the multiple options are found on the first search.
I have found a fix by opening the CHM first and doing the search.
Please test the new version: https://github.com/francostellari/NppPlugins/blob/main/LanguageHelp/LanguageHelp_dll_1v75_x64.zip
Best regards.
